# Generated by Django 4.2.1 on 2023-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("recpt_dt", models.DateTimeField()),
                ("pay_method", models.CharField(max_length=100)),
                ("recpt_amt", models.FloatField(default=0)),
                ("bill_recpt_num", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "SA_Bill_Receipt",
            },
        ),
        migrations.CreateModel(
            name="BillReceiptLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "SA_Bill_Receipt_Line_Item",
            },
        ),
        migrations.CreateModel(
            name="Challan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("challan_number", models.CharField(max_length=100)),
                ("challan_dt", models.DateTimeField()),
            ],
            options={
                "db_table": "SA_Challan",
            },
        ),
        migrations.CreateModel(
            name="ChallanLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("qty", models.BigIntegerField(default=0)),
                ("per_pack_qty", models.BigIntegerField(default=0)),
                ("price", models.FloatField(default=0)),
                ("tax", models.FloatField(default=0)),
                ("disc", models.FloatField(default=0)),
                ("subtotal", models.FloatField(default=0)),
            ],
            options={
                "db_table": "SA_Challan_Line_Item",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("bill_to", models.CharField(blank=True, max_length=264, null=True)),
                ("inv_num", models.CharField(max_length=100)),
                ("inv_dt", models.DateTimeField(auto_now=True)),
                ("payment_method", models.CharField(max_length=100)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Open"),
                            (2, "Partially Paid"),
                            (3, "Fully Paid"),
                            (4, "Cancelled"),
                            (5, "Delivered"),
                        ],
                        default=1,
                    ),
                ),
                ("discount_amount", models.FloatField(default=0)),
                ("tax_amount", models.FloatField(default=0)),
                ("total_amount", models.FloatField(default=0)),
                ("paid_amount", models.FloatField(default=0)),
                ("due_amount", models.FloatField(default=0)),
            ],
            options={
                "db_table": "SA_Invoice",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("qty", models.FloatField(default=0)),
                ("per_pack_qty", models.FloatField(default=0)),
                ("price", models.FloatField(default=0)),
                ("tax", models.FloatField(default=0)),
                ("disc", models.FloatField(default=0)),
                ("subtotal", models.FloatField(default=0)),
            ],
            options={
                "db_table": "SA_Invoice_Line_Item",
            },
        ),
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("ret_dt", models.DateTimeField()),
                ("ref", models.CharField(blank=True, max_length=100, null=True)),
                ("ret_amount", models.FloatField(default=0)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "SA_Sale_Return",
            },
        ),
        migrations.CreateModel(
            name="SaleReturnLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("ret_qty", models.PositiveBigIntegerField(default=0)),
                ("ret_amount", models.FloatField(default=0)),
            ],
            options={
                "db_table": "SA_Sale_Return_Line_Item",
            },
        ),
    ]
