# Generated by Django 4.2.1 on 2023-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="comitted_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
