# Generated by Django 4.2.1 on 2023-09-25 11:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_admin", "0002_alter_preference_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="admin",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="preference",
            name="finance",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="preference",
            name="invoice",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="preference",
            name="product",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="preference",
            name="purchase",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]

