# Generated by Django 4.2.1 on 2023-09-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customgroup",
            name="name",
            field=models.CharField(max_length=150, verbose_name="name"),
        ),
    ]
