# Generated by Django 4.2.1 on 2023-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("bill_num", models.CharField(max_length=100)),
                ("bill_dt", models.DateTimeField(auto_now=True)),
                ("pay_method", models.CharField(max_length=100)),
                ("adv_amt", models.FloatField(default=0)),
                ("cash_amt", models.FloatField(default=0)),
                ("bill_amt", models.FloatField(default=0)),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Partially Bill"),
                            (2, "Fully Bill"),
                            (3, "Waiting For Bill"),
                        ],
                        default=3,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "PROC_Bill_Pay",
            },
        ),
        migrations.CreateModel(
            name="BillPayLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "PROC_Bill_Pay_line_Item",
            },
        ),
        migrations.CreateModel(
            name="PurReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("return_num", models.CharField(max_length=100)),
                ("return_dt", models.DateTimeField(auto_now=True)),
                (
                    "return_note",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("return_amt", models.FloatField(default=0)),
            ],
            options={
                "db_table": "PROC_Pur_Return",
            },
        ),
        migrations.CreateModel(
            name="PurReturnLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("return_qty", models.FloatField(default=0)),
            ],
            options={
                "db_table": "PROC_Pur_Return_Line_Item",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("recpt_num", models.CharField(blank=True, max_length=100, null=True)),
                ("recpt_dt", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Created"), (2, "Closed")],
                        default=1,
                        null=True,
                    ),
                ),
                ("ref_number", models.CharField(blank=True, max_length=250, null=True)),
                ("grand_total", models.FloatField(default=0)),
            ],
            options={
                "db_table": "PROC_Receipt",
            },
        ),
        migrations.CreateModel(
            name="ReceiptLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("lot_number", models.CharField(max_length=100)),
                ("exp_date", models.DateField(blank=True, null=True)),
                ("recpt_qty", models.FloatField(default=0)),
                ("per_pack_qty", models.FloatField(default=0)),
                ("price", models.FloatField(default=0)),
                ("commi", models.FloatField(default=0)),
                ("reciept_identity", models.CharField(max_length=100)),
                ("total_amt", models.FloatField(default=0)),
            ],
            options={
                "db_table": "PROC_Receipt_Line_Item",
            },
        ),
    ]
