# Generated by Django 4.2.1 on 2023-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "collection_num",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("amount", models.FloatField(default=0)),
                ("note", models.CharField(blank=True, max_length=264, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Open"), (2, "Collected"), (2, "Canceled")],
                        default=1,
                    ),
                ),
            ],
            options={
                "db_table": "FM_Collection",
            },
        ),
        migrations.CreateModel(
            name="CustomerReceivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("receivable_num", models.CharField(max_length=20)),
                ("amount", models.FloatField(default=0)),
                ("note", models.CharField(blank=True, max_length=264, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Open"), (2, "Received"), (2, "Canceled")],
                        default=1,
                    ),
                ),
            ],
            options={
                "db_table": "FM_Receivable",
            },
        ),
        migrations.CreateModel(
            name="IncExp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("num", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.PositiveIntegerField()),
                ("source_type", models.PositiveIntegerField()),
                ("dt", models.DateTimeField()),
                ("amt", models.FloatField(default=0)),
                ("ref_num", models.CharField(blank=True, max_length=100, null=True)),
                ("pay_method", models.CharField(blank=True, max_length=100, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "FM_INC_EXP",
            },
        ),
        migrations.CreateModel(
            name="IncExpType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=100)),
                ("code", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "FM_Inc_Exp_Type",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("tran_number", models.CharField(blank=True, max_length=50, null=True)),
                ("tran_date", models.DateTimeField(auto_now=True)),
                ("amount", models.FloatField(default=0)),
                (
                    "tran_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1001, "Receivable against Sales Invoice"),
                            (1002, "Sales Value"),
                            (1003, "Sales Return"),
                            (1004, "Payable against Purchase Receipt"),
                            (1005, "Purchase Value"),
                            (1006, "Purchase Return"),
                            (1007, "Receivable against Others"),
                            (1008, "Collection"),
                            (1009, "Payable against Others"),
                            (1010, "Pay"),
                            (1011, "Salary"),
                            (1012, "Utility"),
                            (1013, "Rent"),
                            (1014, "Advance"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "tran_group",
                    models.IntegerField(
                        choices=[
                            (102, "Income"),
                            (103, "Expense"),
                            (101, "Receivables"),
                            (104, "Payables"),
                        ]
                    ),
                ),
                (
                    "tran_head",
                    models.IntegerField(
                        choices=[
                            (1, "Sales"),
                            (2, "Purchase"),
                            (3, "Customer Dues"),
                            (4, "Vendor Dues"),
                            (5, "General Income"),
                            (6, "General Expense"),
                            (7, "Payroll"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Open"), (2, "Posted")], default=1
                    ),
                ),
            ],
            options={
                "db_table": "FM_Transaction",
            },
        ),
        migrations.CreateModel(
            name="VendorPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("pay_num", models.CharField(max_length=100)),
                ("amt", models.FloatField(default=0)),
                ("note", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "FM_Vendor_Pay",
            },
        ),
        migrations.CreateModel(
            name="VendorPayable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("payable_num", models.CharField(max_length=100)),
                ("amt", models.FloatField(default=0)),
                ("note", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "FM_Vendor_Payable",
            },
        ),
    ]
