# Generated by Django 4.2.1 on 2023-09-24 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_initial"),
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercollection",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_collections",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerreceivable",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_receivables",
                to="customers.customer",
            ),
        ),
    ]
