# Generated by Django 4.2.1 on 2023-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_customercollection_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerreceivable",
            name="comitted_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorpayable",
            name="comitted_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
