# Generated by Django 4.2.1 on 2023-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("advance", models.FloatField(default=0)),
                (
                    "adv_type",
                    models.IntegerField(
                        blank=True, choices=[(1, "Loan"), (2, "Advance")], null=True
                    ),
                ),
            ],
            options={
                "db_table": "HR_Advance",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("week", models.IntegerField(default=0)),
                (
                    "attend_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Present"), (2, "Absent"), (3, "Late")],
                        null=True,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=200, null=True)),
                ("time", models.CharField(max_length=164)),
            ],
            options={
                "db_table": "HR_Attend",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "employee_service_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("doj", models.DateTimeField(blank=True, null=True)),
                (
                    "emp_wage_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Part-Time"), (2, "Full-Time")],
                        null=True,
                    ),
                ),
                ("hr_per_day", models.CharField(blank=True, max_length=50, null=True)),
                ("salary", models.FloatField(default=0)),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Active"), (2, "Terminated")],
                        null=True,
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="")),
                ("addr", models.CharField(blank=True, max_length=500, null=True)),
                ("nid", models.BigIntegerField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("advance_due", models.FloatField(default=0)),
            ],
            options={
                "db_table": "HR_Employee",
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("dt_from", models.DateTimeField(blank=True, null=True)),
                ("dt_to", models.DateTimeField(blank=True, null=True)),
                ("deduct", models.FloatField(default=0)),
                ("advance", models.FloatField(default=0)),
                ("salary", models.FloatField(default=0)),
                ("bonus", models.FloatField(default=0)),
                ("due", models.FloatField(default=0)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Paid"), (2, "Unpaid")], default=2
                    ),
                ),
            ],
            options={
                "db_table": "HR_Salary",
            },
        ),
    ]
